# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aEHdmP8mFtG62bLvomZRyyXn-kfQf7_N
"""

import os
import pandas as pd
import requests
from bs4 import BeautifulSoup
from io import StringIO
from datetime import datetime
from supabase import create_client, Client

# ==========================================
# STAP 1: DATABASE EN SETTINGS INSTELLEN
# ==========================================
SUPABASE_URL = os.environ["SUPABASE_URL"]
SUPABASE_KEY = os.environ["SUPABASE_KEY"]

# Tijdstip van de scrape genereren
scrape_time = datetime.now().isoformat()

# Wikipedia pagina ophalen en tabellen zoeken
headers = {"User-Agent": "StudentAutomationPipeline/1.0"}
url = "https://nl.wikipedia.org/wiki/Religie_in_Belgi%C3%AB"
response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, 'html.parser')
wiki_tabellen = soup.find_all('table', class_='wikitable')

def maak_database_klaar(dataframe):
    """Zorgt ervoor dat NaN-waarden worden omgezet naar None (NULL)
    en dat getallen het juiste type krijgen voor SQL."""
    records = dataframe.to_dict('records')
    schone_records = []
    for row in records:
        schone_rij = {}
        for sleutel, waarde in row.items():
            if pd.isna(waarde):
                schone_rij[sleutel] = None
            elif sleutel == 'jaar' and not pd.isna(waarde):
                schone_rij[sleutel] = int(waarde)
            elif sleutel == 'aantal' and not pd.isna(waarde):
                schone_rij[sleutel] = int(waarde)
            else:
                schone_rij[sleutel] = waarde
        schone_records.append(schone_rij)
    return schone_records

# ==========================================
# STAP 2: SCRAPEN EN OPSCHONEN (MATCHT JOUW DATABASE)
# ==========================================

# --- 1. Eurobarometer ---
euro_tabel = pd.read_html(StringIO(str(wiki_tabellen[0])))[0]
nieuwe_kolommen_euro = {'Religie': 'religie'}
for c in euro_tabel.columns:
    if c != 'Religie':
        nieuwe_kolommen_euro[c] = str(c)[:4]
euro_tabel = euro_tabel.rename(columns=nieuwe_kolommen_euro)

euro_lang = pd.melt(euro_tabel, id_vars=['religie'], var_name='jaar', value_name='percentage')
euro_lang['percentage'] = euro_lang['percentage'].astype(str).str.replace('%', '').str.replace(',', '.')
euro_lang['percentage'] = euro_lang['percentage'].replace('-', pd.NA)
euro_lang['percentage'] = pd.to_numeric(euro_lang['percentage'], errors='coerce')
euro_lang['jaar'] = pd.to_numeric(euro_lang['jaar'], errors='coerce')
euro_lang['scraped_at'] = scrape_time

# --- 2. European Social Survey (ESS) ---
ess_tabel = pd.read_html(StringIO(str(wiki_tabellen[1])))[0]
nieuwe_kolommen_ess = {'Religie': 'religie'}
for c in ess_tabel.columns:
    if c != 'Religie':
        nieuwe_kolommen_ess[c] = str(c)[:4]
ess_tabel = ess_tabel.rename(columns=nieuwe_kolommen_ess)

ess_lang = pd.melt(ess_tabel, id_vars=['religie'], var_name='jaar', value_name='percentage')
ess_lang['percentage'] = ess_lang['percentage'].astype(str).str.replace('%', '').str.replace(',', '.')
ess_lang['percentage'] = pd.to_numeric(ess_lang['percentage'], errors='coerce')
ess_lang['jaar'] = pd.to_numeric(ess_lang['jaar'], errors='coerce')
ess_lang['scraped_at'] = scrape_time

# --- 3. Moslims in België ---
islam_tabel = None
for tabel in wiki_tabellen:
    df = pd.read_html(StringIO(str(tabel)))[0]
    if 'Aantal moslims' in df.columns:
        islam_tabel = df
        break

if islam_tabel is not None:
    islam_tabel['Aantal moslims'] = islam_tabel['Aantal moslims'].astype(str).str.split('[').str[0].str.replace('.', '')
    islam_tabel['Aantal moslims'] = pd.to_numeric(islam_tabel['Aantal moslims'], errors='coerce')
    islam_tabel['Percentage'] = islam_tabel['Percentage'].astype(str).str.replace('%', '').str.replace(',', '.')
    islam_tabel['Percentage'] = pd.to_numeric(islam_tabel['Percentage'], errors='coerce')
    islam_tabel['Jaar'] = pd.to_numeric(islam_tabel['Jaar'], errors='coerce')

    # Hernoemen naar jouw exacte kolommen: jaar, aantal, percentage, scraped_at
    islam_tabel = islam_tabel.rename(columns={'Jaar': 'jaar', 'Aantal moslims': 'aantal', 'Percentage': 'percentage'})
    islam_tabel['scraped_at'] = scrape_time

# ==========================================
# STAP 3: RECHTSTREEKS INSERTEN IN SUPABASE
# ==========================================
try:
    supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

    # 1. Append Eurobarometer
    records_euro = maak_database_klaar(euro_lang)
    supabase.table('eurobarometer').insert(records_euro).execute()

    # 2. Append European Social Survey
    records_ess = maak_database_klaar(ess_lang)
    supabase.table('european_social_survey').insert(records_ess).execute()

    # 3. Append Moslims in België
    if islam_tabel is not None:
        records_islam = maak_database_klaar(islam_tabel)
        supabase.table('moslims_in_belgië').insert(records_islam).execute()

except Exception as e:
    raise RuntimeError(f"Database automation failed: {e}")